@extends('app')

@section('content')

    <section class="collapsed bg-none section" id="content">
        <div class="row">
            <div class="layout">
                <h3 class="section-title">Admin section for lockup.</h3>
                <div role="list" class="grid thirds">
                    <div role="listitem" class="panel button">
                        <a href="{{URL::to("/admin/administrators")}}"
                           style="height: 144px;">
                            <h2>Manage Administrators</h2>
                            <p>Click here to manage and maintain administrators for lockups.</p></a></div>
                    <!--div role="listitem" class="panel button">
                        <a href="{{URL::to("/admin/lockup-dic")}}"
                           style="height: 144px;"><h2>Lockup Dictionary</h2>
                            <p>View various different lockups that are generated by the system.</p>
                        </a></div-->
                    <div role="listitem" class="panel button">
                        <a href="{{URL::to("/admin/downloads")}}"
                           style="height: 144px;"><h2>All Approved Lockups</h2>
                            <p>View the list of all approved locks that can be downloaded.</p>
                        </a></div>
                </div>
            </div>
        </div>
    </section>

@endsection