@extends('app')

@section('content')
        <!-- Form -->


<section class="collapsed bg-none section" id="content">
    <div class="row">
        <div class="layout">
            <div class="text">
                <p> View all lockup that are generated by the application.</p>
                @include("admin.lockup-dictionary-form")
                @foreach($model as $k=>$v)

                    <h5>{{strtoupper($k)}}</h5>
                    <div class="lockup-feed grid halves">

                        @foreach($v as $p)
                            <div class="lockup-well">
                                <article class="feature">
                                    <figure itemtype="http://schema.org/ImageObject" itemscope="itemscope"
                                            class="media image">
                                        @if($p!="")

                                            <div class="lockup svg-preview panel">
                                               {!! $p !!}
                                            </div>

                                        @endif

                                    </figure>
                                    <p>  <a class="modal right" data-reveal-id="viewlockup" id="lockup-view"
                                            href="#">view &raquo;<span class="hideText">{!! $p !!}</span> </a>
                                    </p>

                                </article>
                            </div>
                        @endforeach
                    </div>

                @endforeach

            </div>
        </div>
    </div>
    </div>


    </div>
    </div>

</section>
<div id="viewlockup" class="reveal-modal" data-reveal>
</div>

@endsection




@section('scripts')
    <script type="text/javascript">
        $(document).ready(function () {

            $('.modal').click(function (event) {
                event.preventDefault();
                $('#viewlockup').empty().html("<div class='panel'>" + $(this).find('span.hideText').html() + "<a class=\"close-reveal-modal\" aria-label=\"Close\">&#215;</a></div>");
            });
        });

    </script>
@endsection
